name = "CookieMonster"
uuid = "75086921-2357-4d64-a344-adda719f636f"
authors = ["Johannes Blaschke"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
