name = "Cookie"
uuid = "291bb7ab-538b-46af-bbed-0b035f7a2950"
version = "0.1.0"
authors = ["Johannes Blaschke <johannes.blaschke@gmail.com>"]

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
CookieMonster = "75086921-2357-4d64-a344-adda719f636f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[sources]
CookieMonster = {path = ".."}

[compat]
Comonicon = "1.0.8"
CookieMonster = "0.1.0"
Dates = "1.11.0"
PackageCompiler = "2.4.1"
